on: [push, pull_request]
name: tests
env:
  GO111MODULE: on

jobs:
  linux:
    strategy:
      matrix:
        go-version: [1.13.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1

    # - name: Cache go modules
    #   uses: actions/cache@preview
    #   with:
    #     path: ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #     restore-keys: ${{ runner.os }}-go-

    - name: Run go fmt
      run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Ensure go generate produces a zero diff
      run:  go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)

    - name: Run go vet
      run: GOARCH=wasm GOOS=js go vet ./...

    - name: Run go test
      run: GOARCH=wasm GOOS=js go test -v -coverprofile=coverage.txt -covermode=atomic ./...
